name: Docker Build, Push, and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main      
jobs:
  build-push:
    uses: samalaajaykiran/reusable-workflow-templates-repo-1/.github/workflows/docker-build.yml@main
    with:
      dockerfile: "Dockerfile"
      image-name: "pythonchatapp"
      tag: "v1"
      context: "."
      ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
      ResourceGroup: ${{ vars.AZURE_RESOURCEGROUP }}   
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}  
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        

  deploy:
    needs: build-push
    uses: samalaajaykiran/reusable-workflow-templates-repo-1/.github/workflows/deploy-app-service.yml@main
    with:
      app-name: "python-chat-app-service"
      ResourceGroup: ${{ vars.AZURE_RESOURCEGROUP }}
      image-name: "pythonchatapp"
      acr-login-server: ${{ vars.ACR_LOGIN_SERVER }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}  
